#
# Authors: Krix Apolinario <krixapolinario@gmail.com>
#
# Description: Simples Ansible Playbook to install a Spacewalk 2.6 Server
#

# NOTES
# yum versionlock cglib-2.1.3-4.jpp5
# yum downgrade c3p0 && yum versionlock c3p0-0.9.1.2-2.jpp5
# https://access.redhat.com/solutions/98873
# https://bugzilla.redhat.com/show_bug.cgi?id=1336426
# https://bugzilla.redhat.com/show_bug.cgi?id=1445428
# https://github.com/rharmonson/richtech/wiki/OSVDC-Series:-Configuration-and-Patch-Management-with-Spacewalk-2.6-on-CentOS-7.3.1611-Minimal

---

- name: Check OS version and family
  fail:
    msg: "This role can only be run agaist RHEL 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
    #- ansible_os_family == 'RedHat'
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version | version_compare('7', '!=')

- name: Validate variables
  assert:
    that:
      - ssl_set_country | length == 2

- name: Set hostname
  hostname:
    name: "{{ server_hostname }}"

- name: Copy repo files to yum.repos.d
  copy:
    src: etc/yum.repos.d/
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Download the spacewalk repositorie
  get_url:
    url: http://yum.spacewalkproject.org/RPM-GPG-KEY-spacewalk-2015
    dest: /etc/pki/rpm-gpg/
    mode: 0644

- name: Create spacewalk answers file
  template:
    src: spacewalk-setup-answers.txt.j2
    dest: /tmp/spacewalk-setup-answers.txt

- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest

- name: Install needed packages
  yum: name={{ item }} state=latest
  with_items:
    - libselinux-python
    - yum-plugin-versionlock
    - spacewalk-setup-postgresql
    - spacewalk-postgresql
    - spacewalk-dobby
    - fence-agents-all
    - osad
    - scap-security-guide
    - openscap
    - openscap-utils
    - openscap-python

- name: Set SELinux to enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: Lock version of the cglib package
  shell: yum lockversion cglib-2.1.3-4.jpp5

- name: Downgrade version of the c3p0 package
  shell: yum downgrade c3p0 
  register: downgradec3p0

- name: Lock version of the c3p0 package
  shell: yum versionlock c3p0-0.9.1.2-2.jpp5
  when: downgradec3p0.stdout == ok

- name: Configure Spacewalk Server
  shell: /bin/spacewalk-setup --answer-file=/tmp/spacewalk-setup-answers.txt

- name: Create directory osa-dispatcher.service.d
  file:
    path: /etc/systemd/system/osa-dispatcher.service.d
    state: directory

- name: Copy repo files to osa-dispatcher.service.d
  copy:
    src: etc/systemd/system/osa-dispatcher.service.d/
    dest: /etc/systemd/system/osa-dispatcher.service.d/
    owner: root
    group: root
    mode: 0644
